### ISSUE TITLE
Architecture folder 

### ISSUE THREAD

**Issue by aramrami** [azharanees/OWASP-iGNITA#19]
Hi Azhar,
We need to create an architecture document including all FR and NFR, threat modeling, schema, etc.

All languages used must respect SEI Secure Coding standard.

**Comment by azharanees** [comment]
Sure i will look into it once i complete the development of the scanner MVP

**Comment by azharanees** [comment]
@aramrami the architecture folder is added in docs/scanner branch at [commit](https://github.com/azharanees/OWASP-iGNITA/tree/892ee53788c3d3e47ba60dad403b7e1ab520ddc4)
